name: 'Testing config dependencies and optional configuration'
type: module
package: Testing
# version: VERSION

# Information added by Drupal.org packaging script on 2022-09-16
version: '10.0.0-beta1'
project: 'drupal'
datestamp: 1663358079
